rootProject.name = "cnt-spring-boot"

include("examples:advanced:end-to-end")
include("examples:advanced:scoping")
include("examples:async")
include("examples:basics")
include("examples:caching")
include("examples:data-jdbc")
include("examples:data-jpa")
include("examples:data-mongodb")
include("examples:data-redis")
include("examples:graphql")
include("examples:http-clients")
include("examples:jdbc")
include("examples:messaging-jms-activemq")
include("examples:messaging-jms-artemis")
include("examples:messaging-kafka")
include("examples:messaging-rabbitmq")
include("examples:resilience4j")
include("examples:security")
include("examples:webflux")
include("examples:webmvc")
