name: CI-Build-Job

on:
  workflow_call:
    inputs:
      module:
        description: "The Gradle module to build."
        required: true
        type: string
      name-for-reports:
        description: "The name used as part of the report."
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - run: chmod +x gradlew
      - run: './gradlew ${{ inputs.module }}:build'
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'test-results_${{ inputs.name-for-reports }}'
          path: "**/build/reports/tests"
          retention-days: 7
