name: CI-Build-Job

on:
  workflow_call:
    inputs:
      module:
        description: "The Gradle module to build."
        required: true
        type: string
      name-for-reports:
        description: "The name used as part of the report."
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "liberica"
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      - run: chmod +x gradlew
      - run: './gradlew ${{ inputs.module }}:build'
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: 'test-results_${{ inputs.name-for-reports }}'
          path: "**/build/reports/tests"
          retention-days: 7
