name: CI-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ci_${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-spring-boot:
    runs-on: ubuntu-latest
    needs:
      - advanced-end-to-end
      - advanced-scoping
      - async
      - basics
      - caching
      - data-jdbc
      - data-jpa
      - data-mongodb
      - data-redis
      - graphql
      - http-clients
      - jdbc
      - messaging-jms-activemq
      - messaging-jms-artemis
      - messaging-kafka
      - messaging-rabbitmq
      - micrometer
      - modulith
      - resilience4j
      - scheduling
      - security
      - webflux
      - webmvc
    steps:
      - run: echo "CI-Build completed!"

  advanced-end-to-end:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:advanced:end-to-end'
      name-for-reports: 'advanced-end-to-end'
  advanced-scoping:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:advanced:scoping'
      name-for-reports: 'advanced-scoping'
  async:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:async'
      name-for-reports: 'async'
  basics:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:basics'
      name-for-reports: 'basics'
  caching:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:caching'
      name-for-reports: 'caching'
  data-jdbc:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:data-jdbc'
      name-for-reports: 'data-jdbc'
  data-jpa:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:data-jpa'
      name-for-reports: 'data-jpa'
  data-mongodb:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:data-mongodb'
      name-for-reports: 'data-mongodb'
  data-redis:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:data-redis'
      name-for-reports: 'data-redis'
  graphql:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:graphql'
      name-for-reports: 'graphql'
  http-clients:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:http-clients'
      name-for-reports: 'http-clients'
  jdbc:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:jdbc'
      name-for-reports: 'jdbc'
  messaging-jms-activemq:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:messaging-jms-activemq'
      name-for-reports: 'messaging-jms-activemq'
  messaging-jms-artemis:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:messaging-jms-artemis'
      name-for-reports: 'messaging-jms-artemis'
  messaging-kafka:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:messaging-kafka'
      name-for-reports: 'messaging-kafka'
  messaging-rabbitmq:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:messaging-rabbitmq'
      name-for-reports: 'messaging-rabbitmq'
  micrometer:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:micrometer'
      name-for-reports: 'micrometer'
  modulith:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:modulith'
      name-for-reports: 'modulith'
  resilience4j:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:resilience4j'
      name-for-reports: 'resilience4j'
  scheduling:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:scheduling'
      name-for-reports: 'scheduling'
  security:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:security'
      name-for-reports: 'security'
  webmvc:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:webmvc'
      name-for-reports: 'webmvc'
  webflux:
    uses: ./.github/workflows/_build.yml
    with:
      module: ':examples:webflux'
      name-for-reports: 'webflux'
